name: Trigger auto deployment for container-app-zofdo2a2hkio2

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/container-app-zofdo2a2hkio2-AutoDeployTrigger-9e6f30ee-70ef-4162-be54-bd37fc1fa991.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPZOFDO2A2HKIO2_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPZOFDO2A2HKIO2_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPZOFDO2A2HKIO2_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: defaultacrcontainerregistryaffa.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPPZOFDO2A2HKIO2_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPZOFDO2A2HKIO2_REGISTRY_PASSWORD }}
          containerAppName: container-app-zofdo2a2hkio2
          resourceGroup: djangoappspaces89eeb10e
          imageToBuild: defaultacrcontainerregistryaffa.azurecr.io/container-app-zofdo2a2hkio2:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


